spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/restaurant_recommend?useSSL=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true

service:
  authUrl: "http://sso.dreamspark.com.cn:8080/user/login"






